default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id:   black
        exclude: migrations
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)

# uncomment once the repo complies with flake8
#-   repo: https://github.com/pycqa/flake8
#    rev: 5.0.4
#    hooks:
#    -   id: flake8
#        args: ["--ignore=E501, W503"]